### ISSUE TITLE
blank page (OSX)

### ISSUE THREAD

**Issue by sogen** [documize/community#105]
using community release 1.50 on OSX Sierra

1.- brew install mysql 
2.- brew services start mysql
3.- create database documize;
4.- grant 
5.- exit mysql
6.-sudo chmod 755 documize
7.- ran
`./documize-community-darwin-amd64 -port=5001 -db='root@tcp(localhost:3306)/documize' -salt=1234567890acbdefg
`
8.- navigated to localhost

9.- blank page

Terminal says:

```
INFO[0013]  URL not found                                env=Non-production

ERRO[0147] Unable to prepare select for subdomain        env=Non-production error=Error 1146: Table 'documize.organization' doesn't exist stack=goroutine 16 [running]:
github.com/documize/community/core/log.Error(0xc4204629c0, 0x27, 0x1a2b560, 0xc42021e4e0)

```

**Comment by sogen** [comment]
updated steps

**Comment by sogen** [comment]
Chrome console:



```
documize-8f1275f….js:589 o {description: undefined, fileName: undefined, lineNumber: undefined, message: "Request was rejected because user is not permitted to perform this operation.", name: "Error"…}
documize-8f1275f….js:589 _ {state: y, intent: n, router: A, data: Object, resolvedModels: Object…}
vendor-f6c6a54….js:2321 Error while processing route: folders Request was rejected because user is not permitted to perform this operation. Error
    at o.n (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6282:3)
    at o (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6282:179)
    at o.handleResponse (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6311:40)
    at o.handleResponse (http://localhost:5001/assets/documize-8f1275f463d9e9ea73c4e657b8881eb3.js:595:117)
    at o.n [as handleResponse] (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:2776:9)
    at Object.<anonymous> (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6299:88)
    at u (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:246:118)
    at Object.fireWith [as rejectWith] (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:247:716)
    at r (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:434:455)
    at XMLHttpRequest.<anonymous> (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:462:194)
h @ vendor-f6c6a54….js:2321
error @ vendor-f6c6a54….js:2402
y @ vendor-f6c6a54….js:2328
d @ vendor-f6c6a54….js:2996
trigger @ vendor-f6c6a54….js:3081
(anonymous) @ vendor-f6c6a54….js:3019
T @ vendor-f6c6a54….js:3160
A @ vendor-f6c6a54….js:3161
C @ vendor-f6c6a54….js:3159
w @ vendor-f6c6a54….js:3157
e.invokeWithOnError @ vendor-f6c6a54….js:1101
e.flush @ vendor-f6c6a54….js:1092
e.flush @ vendor-f6c6a54….js:1103
e.end @ vendor-f6c6a54….js:1110
e.run @ vendor-f6c6a54….js:1120
e.join @ vendor-f6c6a54….js:1120
je.join @ vendor-f6c6a54….js:2048
(anonymous) @ vendor-f6c6a54….js:6299
u @ vendor-f6c6a54….js:246
fireWith @ vendor-f6c6a54….js:247
r @ vendor-f6c6a54….js:434
(anonymous) @ vendor-f6c6a54….js:462
vendor-f6c6a54….js:1895 Request was rejected because user is not permitted to perform this operation.
Error
    at o.n (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6282:3)
    at o (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6282:179)
    at o.handleResponse (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6311:40)
    at o.handleResponse (http://localhost:5001/assets/documize-8f1275f463d9e9ea73c4e657b8881eb3.js:595:117)
    at o.n [as handleResponse] (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:2776:9)
    at Object.<anonymous> (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:6299:88)
    at u (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:246:118)
    at Object.fireWith [as rejectWith] (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:247:716)
    at r (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:434:455)
    at XMLHttpRequest.<anonymous> (http://localhost:5001/assets/vendor-f6c6a542fbbb1d6f3b6c606faa5ff6c9.js:462:194)

```

**Comment by HarveyKandola** [comment]
Investigating as we type...stay tuned

**Comment by HarveyKandola** [comment]
Please pull and try latest release (1.50.1)

**Comment by sogen** [comment]
thx

**Comment by sogen** [comment]
Good: installed fine
