### ISSUE TITLE
Unicode tags don't seem to be supported?

### ISSUE THREAD

**Issue by andreis** [documize/community#109]
![screen shot 2017-08-05 at 22 52 20](https://user-images.githubusercontent.com/1249760/28998344-e8d478e0-7a30-11e7-8c77-bd75a070a587.png)

Tried to name a tag "🅱ig🅱ois" (don't ask) and I get an error, the tag is also gone after refreshing the page.

```

vendor-50f4bf9….js:1895 Request was formatted incorrectly.
Error
    at a.n (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6282:3)
    at a (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6282:288)
    at o.handleResponse (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6313:41)
    at o.handleResponse (https://documize.portablecloud.net/assets/documize-5780200ea37c4f46875edf56984ea043.js:595:117)
    at o.n [as handleResponse] (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:2776:9)
    at Object.<anonymous> (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6299:88)
    at u (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:246:118)
    at Object.fireWith [as rejectWith] (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:247:716)
    at r (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:434:455)
    at XMLHttpRequest.<anonymous> (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:462:194)
vendor-50f4bf9….js:1895 Request was formatted incorrectly.
Error
    at a.n (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6282:3)
    at a (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6282:288)
    at o.handleResponse (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6313:41)
    at o.handleResponse (https://documize.portablecloud.net/assets/documize-5780200ea37c4f46875edf56984ea043.js:595:117)
    at o.n [as handleResponse] (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:2776:9)
    at Object.<anonymous> (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:6299:88)
    at u (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:246:118)
    at Object.fireWith [as rejectWith] (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:247:716)
    at r (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:434:455)
    at XMLHttpRequest.<anonymous> (https://documize.portablecloud.net/assets/vendor-50f4bf95796063a8999f8910a37dbaa2.js:462:194)
```

**Comment by andreis** [comment]
Browser:

Version 59.0.3071.115 (Official Build) (64-bit)

OS:

MacOS 10.12.5 (16F73)

**Comment by HarveyKandola** [comment]
Thanks @andreis 

Fixed for next release, will merge into master branch shortly.

See #102 for utf8mb4 discussion

**Comment by andreis** [comment]
Haha you're crushing it!
