### ISSUE TITLE
Panic on setup

### ISSUE THREAD

**Issue by Zevran** [documize/community#117]
Hi,

When I try to go through the setup the application goes wrong with a panic message :
```
Database checks: started
Database checks: SQL variant UNKNOWN
Database checks: SQL version 5.7.19-0ubuntu0.16.04.1
Entering database set-up mode because the database is empty.....
Registered 9 sections
Starting Community Edition version 1.53.0
Serving SETUP web server
Starting non-SSL server on 5000
***
*** Go to http://localhost:5000/setup in your web browser and complete setup wizard ***
***
[negroni] listening on :5000
documize
f6e3ae120c
documize
f6e3ae120c
Database checks: will execute the following update files: db_00000.sql, db_00001.sql, db_00002.sql, db_00003.sql, db_00004.sql, db_00005.sql, db_00006.sql, db_00007.sql, db_00008.sql, db_00009.sql, db_00010.sql, db_00011.sql, db_00012.sql, db_00013.sql, db_00014.sql, db_00015.sql
Processing migration file: db_00000.sql
Processing migration file: db_00001.sql
Processing migration file: db_00002.sql
Processing migration file: db_00003.sql
Processing migration file: db_00004.sql
Processing migration file: db_00005.sql
Processing migration file: db_00006.sql
Processing migration file: db_00007.sql
Processing migration file: db_00008.sql
Processing migration file: db_00009.sql
Processing migration file: db_00010.sql
Processing migration file: db_00011.sql
Processing migration file: db_00012.sql
Processing migration file: db_00013.sql
Processing migration file: db_00014.sql
Processing migration file: db_00015.sql
Database checks: completed
2017/08/28 08:32:09 http: panic serving 10.0.2.2:53102: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc420314dc0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0xa7ca40, 0x10be360)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/documize/community/domain/meta.(*Handler).Meta(0xc42013f650, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/domain/meta/endpoint.go:42 +0x8f
github.com/documize/community/domain/meta.(*Handler).Meta-fm(0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/server/routing/routes.go:66 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42013f6e0, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1942 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201be820, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00, 0xc4201a8840)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4201c1540, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00, 0xc4201a8840)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc4201c1540, 0xc4201c15a0, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).cors(0xc42013f620, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00, 0xc4201a8820)
	src/github.com/documize/community/server/middleware.go:51 +0x185
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.cors)-fm(0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00, 0xc4201a8820)
	src/github.com/documize/community/server/server.go:66 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42013fcc0, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00, 0xc4201a8820)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc42013fcc0, 0xc4201c1580, 0x7fad651d9178, 0xc4201a6980, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc42014bd10, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x118
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201b0910, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42032a520, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc42032a520, 0xc42032a5a0, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).metrics(0xc42013f620, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87c0)
	src/github.com/documize/community/server/middleware.go:61 +0x137
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.metrics)-fm(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87c0)
	src/github.com/documize/community/server/server.go:85 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420326860, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87c0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc420326860, 0xc42032a580, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).cors(0xc42013f620, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87a0)
	src/github.com/documize/community/server/middleware.go:51 +0x185
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.cors)-fm(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87a0)
	src/github.com/documize/community/server/server.go:66 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420326850, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a87a0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc420326850, 0xc42032a560, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc420309200, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00, 0xc4201a8720)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/static.go:49 +0x71c
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe392a0, 0xc420309200, 0xc42032a540, 0x7fad651d9178, 0xc4201a6900, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc4203091a0, 0xe3f720, 0xc420149960, 0xc4200b8a00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x118
net/http.serverHandler.ServeHTTP(0xc4201b28f0, 0xe3f720, 0xc420149960, 0xc4200b8a00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420314dc0, 0xe401e0, 0xc42019a0c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
2017/08/28 08:32:09 http: panic serving 10.0.2.2:53114: runtime error: invalid memory address or nil pointer dereference
goroutine 29 [running]:
net/http.(*conn).serve.func1(0xc420258280)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0xa7ca40, 0x10be360)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/documize/community/domain/meta.(*Handler).Meta(0xc42013f650, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/domain/meta/endpoint.go:42 +0x8f
github.com/documize/community/domain/meta.(*Handler).Meta-fm(0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/server/routing/routes.go:66 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42013f6e0, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1942 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201be820, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00, 0xc4201c0800)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4201c1540, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00, 0xc4201c0800)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc4201c1540, 0xc4201c15a0, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).cors(0xc42013f620, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00, 0xc4201c07e0)
	src/github.com/documize/community/server/middleware.go:51 +0x185
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.cors)-fm(0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00, 0xc4201c07e0)
	src/github.com/documize/community/server/server.go:66 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42013fcc0, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00, 0xc4201c07e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc42013fcc0, 0xc4201c1580, 0x7fad651d9178, 0xc4201e3a00, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc42014bd10, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x118
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201b0910, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:98 +0x255
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0780)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42032a520, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0780)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc42032a520, 0xc42032a5a0, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).metrics(0xc42013f620, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0760)
	src/github.com/documize/community/server/middleware.go:61 +0x137
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.metrics)-fm(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0760)
	src/github.com/documize/community/server/server.go:85 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420326860, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0760)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc420326860, 0xc42032a580, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).cors(0xc42013f620, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c06a0)
	src/github.com/documize/community/server/middleware.go:51 +0x185
github.com/documize/community/server.(*middleware).(github.com/documize/community/server.cors)-fm(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c06a0)
	src/github.com/documize/community/server/server.go:66 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420326850, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c06a0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe3b020, 0xc420326850, 0xc42032a560, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc420309200, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00, 0xc4201c0600)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/static.go:49 +0x71c
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe392a0, 0xc420309200, 0xc42032a540, 0x7fad651d9178, 0xc4201e39c0, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xb4
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc4203091a0, 0xe3f720, 0xc42038a540, 0xc4200b8c00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x118
net/http.serverHandler.ServeHTTP(0xc4201b28f0, 0xe3f720, 0xc42038a540, 0xc4200b8c00)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420258280, 0xe401e0, 0xc4201e3840)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
```

I tried with the exact same command as described in the documentation
```bash
./documize-community-linux-amd64 -port 5000 -db 'root:password@tcp(127.0.0.1:3306)/documize' -salt 1234567890acbdefg
```

NB: I got the same error when I tried to run it on my mac os.

Thanks

**Comment by HarveyKandola** [comment]
Could you test with latest release please?

https://github.com/documize/community/releases/tag/v1.53.1

**Comment by Zevran** [comment]
Same thing with the latest release ...

**Comment by HarveyKandola** [comment]
We have managed to replicate the issue on Ubuntu and are working on resolving it ASAP.

**Comment by HarveyKandola** [comment]
Please try latest release as we think the issue has been resolved.

On Ubuntu, MySQL can return non-standard version information and hence we have:

1. Improve database detection 
2. Added new optional "dbtype" command line switch which can be set to mysql|percona|mariadb (environment variable name is DOCUMIZEDBTYPE)

Trash your database and try again.

**Comment by Zevran** [comment]
Nice ! It's working !

Thank you !
