### ISSUE TITLE
[MariaDB 10.3] Error in SQL-Syntax 

### ISSUE THREAD

**Issue by enoch85** [documize/community#140]
Just tried to setup Documize and got this when hitting "Setup".

*Passwords are not the actual passwords*

```
root@wiki01:/bin# documize-community-linux-amd64 -port=5001 -db='root:PlLKJDBCKJBDAGCvjOw6qX@tcp(localhost:3306)/documize' -dbtype=mariadb -salt ccfAd1dbb2b74bff2

Database checks: started
Database checks: SQL variant MariaDB
Database checks: SQL version 10.3.5-MariaDB-10.3.5+maria~xenial-log
Entering database set-up mode because the database is empty.....
Registered 10 sections
Starting Community Edition version 1.59.0
Serving SETUP web server
Starting non-SSL server on 5001
***
*** Go to http://localhost:5001/setup in your web browser and complete setup wizard ***
***
[negroni] listening on :5001
Database checks: will execute the following update files: db_00000.sql, db_00001.sql, db_00002.sql, db_00003.sql, db_00004.sql, db_00005.sql, db_00006.sql, db_00007.sql, db_00008.sql, db_00009.sql, db_00010.sql, db_00011.sql, db_00012.sql, db_00013.sql, db_00014.sql, db_00015.sql, db_00016.sql, db_00017.sql, db_00018.sql, db_00019.sql
Processing migration file: db_00000.sql
Processing migration file: db_00001.sql
Processing migration file: db_00002.sql
Processing migration file: db_00003.sql
Processing migration file: db_00004.sql
Processing migration file: db_00005.sql
Processing migration file: db_00006.sql
Processing migration file: db_00007.sql
Processing migration file: db_00008.sql
Processing migration file: db_00009.sql
Processing migration file: db_00010.sql
Processing migration file: db_00011.sql
Processing migration file: db_00012.sql
Processing migration file: db_00013.sql
Processing migration file: db_00014.sql
Processing migration file: db_00015.sql
Processing migration file: db_00016.sql
Processing migration file: db_00017.sql
Processing migration file: db_00018.sql
Processing migration file: db_00019.sql
Database checks: failed: 
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE user ADD COLUMN `lastversion` CHAR(16) NOT NULL DEFAULT '' AFTER `ac' at line 6
goroutine 27 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc42009a9b0, 0x4f5200, 0xb4c18d, 0x19, 0xbd1460, 0xc42000a180)
	/Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.migrateEnd(0xc420074600, 0xc420194540, 0xbd1460, 0xc42000a180, 0xc420194501, 0x0, 0x0)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:161 +0xc6
github.com/documize/community/core/database.Migrate(0xc420074600, 0x70d826400, 0x11b91c0, 0x8)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:228 +0x3a1
github.com/documize/community/core/database.(*Handler).Setup(0xc42023c130, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:92 +0x5f4
github.com/documize/community/core/database.(*Handler).Setup-fm(0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42023c140, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202767e0, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fede1e65370, 0xc42000c030, 0xc420436300, 0xc42040e160)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420357e40, 0x7fede1e65370, 0xc42000c030, 0xc420436300, 0xc42040e160)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd23a0, 0xc420357e40, 0xc420357ea0, 0x7fede1e65370, 0xc42000c030, 0xc420436300)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fede1e65370, 0xc42000c030, 0xc420436300)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc42023c230, 0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:203 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42023ced0, 0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd23a0, 0xc42023ced0, 0xc420357e80, 0x7fede1e65370, 0xc42000c030, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc42039e600, 0x7fede1e65370, 0xc42000c028, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201f12d0, 0x7fede1e65370, 0xc42000c028, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fede1e653
database.Setup migrate
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE user ADD COLUMN `lastversion` CHAR(16) NOT NULL DEFAULT '' AFTER `ac' at line 6
goroutine 27 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc42009a9b0, 0xc420194500, 0xb49f19, 0x16, 0xbd1460, 0xc42000a180)
	/Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.(*Handler).Setup(0xc42023c130, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:93 +0x7c1
github.com/documize/community/core/database.(*Handler).Setup-fm(0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42023c140, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202767e0, 0x7fede1e65370, 0xc42000c030, 0xc420436500)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fede1e65370, 0xc42000c030, 0xc420436300, 0xc42040e160)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420357e40, 0x7fede1e65370, 0xc42000c030, 0xc420436300, 0xc42040e160)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd23a0, 0xc420357e40, 0xc420357ea0, 0x7fede1e65370, 0xc42000c030, 0xc420436300)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fede1e65370, 0xc42000c030, 0xc420436300)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc42023c230, 0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:203 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42023ced0, 0x7fede1e65370, 0xc42000c030, 0xc420436200, 0xc42040e140)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd23a0, 0xc42023ced0, 0xc420357e80, 0x7fede1e65370, 0xc42000c030, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc42039e600, 0x7fede1e65370, 0xc42000c028, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201f12d0, 0x7fede1e65370, 0xc42000c028, 0xc420436200)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fede1e65370, 0xc42000c028, 0xc420436000, 0xc42040e120)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4203a9e20, 0x7fede1e65370, 0xc42000c028, 0xc420436000, 0xc42040e120)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangs
```

**Comment by HarveyKandola** [comment]
Try the -dbtype=mariadb switch:



https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/VzSL8cVZ4QAB2B4Y/environment-variables-and-command-lines-switches

**Comment by enoch85** [comment]
I updated the post. I already used that, following the instructions from the documentation.

**Comment by HarveyKandola** [comment]
thanks -- we'll jump on this ASAP and provide a resolution.

**Comment by HarveyKandola** [comment]
We believe this is now fixed, download again please and try it.

https://storage.googleapis.com/documize/downloads/documize-community-darwin-amd64
https://storage.googleapis.com/documize/downloads/documize-community-linux-amd64
https://storage.googleapis.com/documize/downloads/documize-community-windows-amd64.exe

**Comment by enoch85** [comment]
Thank you! I love the responsiveness for this issue. Great work!
