### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by justinedwards** [documize/community#142]
I just tried to setup documize and I received the following error. This is the command I used to start the setup server:
`./documize-community-linux-amd64 -port=3001 -db='root:<db_password>@tcp(<remote_host>:3306)/documize' -dbtype=mysql -salt=y2k1z2im5tk50uufr`

The moment I click to begin, I receive this error. It _seems_ to have something to do with the key in the config table, but I'm not sure. I ran everything in https://github.com/documize/community/tree/master/core/database/scripts/autobuild in a separate database and once I fixed the field length of the `key` column of the `setup` table, it ran all of the remaining scripts without issue.

Let me know if I'm missing a step. I am indeed running MySQL 5.7.19-log.

```
Database checks: started
Database checks: SQL variant MySQL
Database checks: SQL version 5.7.19-log
Entering database set-up mode because the database is empty.....
Registered 10 sections
Starting Community Edition version 1.60.0
Serving SETUP web server
Starting non-SSL server on 3001
***
*** Go to http://localhost:3001/setup in your web browser and complete setup wizard ***
***
[negroni] listening on :3001
Database checks: will execute the following update files: db_00000.sql, db_00001.sql, db_00002.sql, db_00003.sql, db_00004.sql, db_00005.sql, db_00006.sql, db_00007.sql, db_00008.sql, db_00009.sql, db_00010.sql, db_00011.sql, db_00012.sql, db_00013.sql, db_00014.sql, db_00015.sql, db_00016.sql, db_00017.sql, db_00018.sql, db_00019.sql
Processing migration file: db_00000.sql
Database checks: failed:
Error 1071: Specified key was too long; max key length is 1000 bytes
goroutine 81 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc4200c6730, 0x4f5200, 0xb4d73e, 0x19, 0xbd2f80, 0xc4202a2f60)
        /Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.migrateEnd(0xc4200c8300, 0xc420464510, 0xbd2f80, 0xc4202a2f60, 0xc420464501, 0x0, 0x0)
        /Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:161 +0xc6
github.com/documize/community/core/database.Migrate(0xc4200c8300, 0x3cd384000, 0x11bc360, 0x8)
        /Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:228 +0x3a1
github.com/documize/community/core/database.(*Handler).Setup(0xc4202a8220, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:92 +0x5f4
github.com/documize/community/core/database.(*Handler).Setup-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202a8230, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203375e0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500, 0xc420506a40)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420462ac0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500, 0xc420506a40)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd3ec0, 0xc420462ac0, 0xc420462b20, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc4202a8320, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:203 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4202a8fd0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd3ec0, 0xc4202a8fd0, 0xc420462b00, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc420464e70, 0x7fed486ee0a0, 0xc4205300d0, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202f20e0, 0x7fed486ee0a0, 0xc4205300d0, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fed486ee0
database.Setup migrate
Error 1071: Specified key was too long; max key length is 1000 bytes
goroutine 81 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc4200c6730, 0xc420464500, 0xb4b4b3, 0x16, 0xbd2f80, 0xc4202a2f60)
        /Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.(*Handler).Setup(0xc4202a8220, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:93 +0x7c1
github.com/documize/community/core/database.(*Handler).Setup-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202a8230, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203375e0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f700)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500, 0xc420506a40)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc420462ac0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500, 0xc420506a40)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd3ec0, 0xc420462ac0, 0xc420462b20, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f500)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc4202a8320, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:203 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4202a8fd0, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400, 0xc420506a20)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xbd3ec0, 0xc4202a8fd0, 0xc420462b00, 0x7fed486ee0a0, 0xc4205300d8, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc420464e70, 0x7fed486ee0a0, 0xc4205300d0, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202f20e0, 0x7fed486ee0a0, 0xc4205300d0, 0xc42018f400)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fed486ee0a0, 0xc4205300d0, 0xc4201e6b00, 0xc420506a00)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4205063e0, 0x7fed486ee0a0, 0xc4205300d0, 0xc4201e6b00, 0xc420506a00)
        /Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangs

```

Thanks for the help!

**Comment by mcmatts** [comment]
It could a problem when creating the unique constraint on the ```config``` table.

We are unable to reproduce it at the moment. You running standard MySQL distro?

This setting might help to isolate the issue:

https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

**Comment by justinedwards** [comment]
That parameter has already been set. I do have circular replication setup. Yes, standard MySQL distro.

**Comment by mcmatts** [comment]
@justinedwards thanks.

Suspect the issue is with the ENGINE being used on that ```config``` table.

Default in scripts right now: ENGINE = InnoDB

https://github.com/documize/community/blob/527b02e8b385ff5d2c93b4f661da831325546a33/core/database/scripts/autobuild/db_00000.sql#L257

Change to ENGINE = InnoDB like this:

https://github.com/documize/community/blob/527b02e8b385ff5d2c93b4f661da831325546a33/core/database/scripts/autobuild/db_00000.sql#L253

InnoDB has greater unqiue key length.

**Comment by justinedwards** [comment]
My default engine was MyISAM. I've changed it to InnoDB and it worked.
```
CREATE TABLE IF NOT EXISTS `config` (
	`key` CHAR(255) NOT NULL,
	`config` JSON,
	UNIQUE INDEX `idx_config_area` (`key` ASC))
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE=InnoDB;
```

Thanks again! It may still be worth modifying the source.

**Comment by mcmatts** [comment]
@justinedwards fixed for next release (due next week).
