### ISSUE TITLE
Crash on setup

### ISSUE THREAD

**Issue by alexbilbie** [documize/community#155]
I've just downloaded the community MacOS build and run it like so:

```
./documize-community-darwin-amd64 -db 'root:password@tcp(127.0.0.1:3306)/mydb' -dbtype mysql -salt gGbc4C2fc339Y3b8a -port 8080
```

When I fill out the initial setup page (that asks for team name, email, password, etc) I get the following crash:

```
Database checks: started
Database checks: SQL variant MySQL
Database checks: SQL version 5.7.22
Entering database set-up mode because the database is empty.....
Registered 10 sections
Starting Community Edition version 1.64.4
Serving SETUP web server
Starting non-SSL server on 8080
***
*** Go to http://localhost:8080/setup in your web browser and complete setup wizard ***
***
[negroni] listening on :8080
Database checks: will execute the following update files: db_00000.sql, db_00001.sql, db_00002.sql, db_00003.sql, db_00004.sql, db_00005.sql, db_00006.sql, db_00007.sql, db_00008.sql, db_00009.sql, db_00010.sql, db_00011.sql, db_00012.sql, db_00013.sql, db_00014.sql, db_00015.sql, db_00016.sql, db_00017.sql, db_00018.sql, db_00019.sql, db_00020.sql, db_00021.sql, db_00022.sql, db_00023.sql
Processing migration file: db_00000.sql
Processing migration file: db_00001.sql
Processing migration file: db_00002.sql
Processing migration file: db_00003.sql
Processing migration file: db_00004.sql
Processing migration file: db_00005.sql
Processing migration file: db_00006.sql
Processing migration file: db_00007.sql
Processing migration file: db_00008.sql
Processing migration file: db_00009.sql
Processing migration file: db_00010.sql
Processing migration file: db_00011.sql
Processing migration file: db_00012.sql
Processing migration file: db_00013.sql
Processing migration file: db_00014.sql
Processing migration file: db_00015.sql
Database checks: failed:
Error 1: Can't create/write to file './documize/db.opt' (Errcode: 2 - No such file or directory)
goroutine 36 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc4200ae7d0, 0x10f3c00, 0x169b1e9, 0x19, 0x1740460, 0xc42018b600)
	/Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.migrateEnd(0xc420001980, 0xc4202da0f0, 0x1740460, 0xc42018b600, 0xc4202da001, 0x0, 0x0)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:161 +0xc6
github.com/documize/community/core/database.Migrate(0xc420001980, 0x4bf839f00, 0x1ccac40, 0x8)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/migrate.go:228 +0x3a1
github.com/documize/community/core/database.(*Handler).Setup(0xc42018c2d0, 0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:92 +0x5f4
github.com/documize/community/core/database.(*Handler).Setup-fm(0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42018c2e0, 0x4000020, 0xc42018e080, 0xc42041b000)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420293d50, 0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x4000020, 0xc42018e080, 0xc42041ae00, 0xc42018a320)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4203b4dc0, 0x4000020, 0xc42018e080, 0xc42041ae00, 0xc42018a320)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0x17413c0, 0xc4203b4dc0, 0xc4203b4e20, 0x4000020, 0xc42018e080, 0xc42041ae00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x4000020, 0xc42018e080, 0xc42041ae00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc42018c3d0, 0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:207 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42018d150, 0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0x17413c0, 0xc42018d150, 0xc4203b4e00, 0x4000020, 0xc42018e080, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc4203bd1d0, 0x4000020, 0xc42018e078, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42024a0e0, 0x4000020, 0xc42018e078, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x4000020, 0xc42018e078, 0xc42041ab00, 0xc42018a2c0)
	/Users/Raven/code/go
database.Setup migrate
Error 1: Can't create/write to file './documize/db.opt' (Errcode: 2 - No such file or directory)
goroutine 36 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc4200ae7d0, 0xc4202da000, 0x1699374, 0x16, 0x1740460, 0xc42018b600)
	/Users/Raven/code/go/src/github.com/documize/community/edition/logging/logger.go:51 +0x168
github.com/documize/community/core/database.(*Handler).Setup(0xc42018c2d0, 0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/core/database/endpoint.go:93 +0x7c1
github.com/documize/community/core/database.(*Handler).Setup-fm(0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:42 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42018c2e0, 0x4000020, 0xc42018e080, 0xc42041b000)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:1947 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420293d50, 0x4000020, 0xc42018e080, 0xc42041b000)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x4000020, 0xc42018e080, 0xc42041ae00, 0xc42018a320)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4203b4dc0, 0x4000020, 0xc42018e080, 0xc42041ae00, 0xc42018a320)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0x17413c0, 0xc4203b4dc0, 0xc4203b4e20, 0x4000020, 0xc42018e080, 0xc42041ae00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x4000020, 0xc42018e080, 0xc42041ae00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc42018c3d0, 0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/server/middleware.go:207 +0x224
github.com/documize/community/server.(*middleware).Authorize-fm(0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42018d150, 0x4000020, 0xc42018e080, 0xc42041ad00, 0xc42018a2e0)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0x17413c0, 0xc42018d150, 0xc4203b4e00, 0x4000020, 0xc42018e080, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc4203bd1d0, 0x4000020, 0xc42018e078, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xf2
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42024a0e0, 0x4000020, 0xc42018e078, 0xc42041ad00)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x4000020, 0xc42018e078, 0xc42041ab00, 0xc42018a2c0)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4203e4e60, 0x4000020, 0xc42018e078, 0xc42041ab00, 0xc42018a2c0)
	/Users/Raven/code/go/src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github
```

Re-running the binary has a similar error complaining about not being able to write to `./documize/db.opt`. I tried creating that file (using mkdir + touch) but it still fails.

**Comment by sauls8t** [comment]
Startup command looks good. 

The error occurs when attempting to commit the DB changes.

```db.opt``` file suggests a MySQL issue as this is a MySQL specific file.

We are still investigating...

**Comment by alexbilbie** [comment]
@sauls8t yep started with Docker like so:

`docker run -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE= mydb -p 3306:3306 mysql:5.7 --character-set-server=utf8mb4`

**Comment by sauls8t** [comment]
Seems like an issue with MySQL running under Docker.

We see the same issue with Docker MySQL 5.7x series.

Not found a solution yet...

**Comment by louisyssel** [comment]
I have exactly the same problem, and I am not running mysql on Docker, however, my mysql server is not on the same server.
I am also running mysql 5.7. When I look at the mysql server, the tables were created and is all there. 23 I think. but I still get the same error.

**Comment by louisyssel** [comment]
I just resolved this by dropping the database, recreating it, and then starting the server again, and this time it went through fine.
