### ISSUE TITLE
Cannot create space[postgresql]

### ISSUE THREAD

**Issue by countstarlight** [documize/community#194]
version: v2.0.1 documize-community-linux-amd64

Cannot create space with `PostgreSQL`:

```
Database: checking state
Database: provider name PostgreSQL
Database: provider version 90610
Database: current version number is 3
Database: loaded 3 SQL scripts for provider PostgreSQL
Database: 0 scripts to process
Extensions: registered 11 section types
Product: Community Edition version 2.0.1 (build 190127153032)
Web Server: starting up
Web Server: binding non-SSL server on 3001
[negroni] listening on :3001
space.add
unable to execute insert for space: pq: value too long for type character varying(20)
goroutine 63 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc00007a640, 0x0, 0xb9f136, 0x9, 0xd10f60, 0xc000
482000)
        src/github.com/documize/community/edition/logging/logger.go:56 +0x168
github.com/documize/community/domain/space.(*Handler).Add(0xc00019b580, 0x7f926151aaa0, 0xc0003e5e28, 0xc0004f1300)
        src/github.com/documize/community/domain/space/endpoint.go:118 +0x361c
github.com/documize/community/domain/space.(*Handler).Add-fm(0x7f926151aaa0, 0xc0003e5e28, 0xc0004f1300)
        src/github.com/documize/community/server/routing/routes.go:146 +0x48
net/http.HandlerFunc.ServeHTTP(0xc00019ba40, 0x7f926151aaa0, 0xc0003e5e28, 0xc0004f1300)
```

**Comment by sauls8t** [comment]
Try a smaller space description when defining new space?

We'll fix that up in next release.

**Comment by countstarlight** [comment]
@sauls8t Maybe it not cause by description, I create a new space with `test` as name, empty description and default icon, it works. But if select another icon or edit an exists space to a new icon and save, it cannot work:
![DeepinScreenshot_select-area_20190202103604.png](https://i.loli.net/2019/02/02/5c550336e2da9.png)
```
Database: checking state
Database: provider name PostgreSQL
Database: provider version 100005
Database: current version number is 3
Database: loaded 3 SQL scripts for provider PostgreSQL
Database: 0 scripts to process
Extensions: registered 11 section types
Product: Community Edition version 2.0.1 (build 190127153032)
Web Server: starting up
Web Server: binding non-SSL server on 3001
[negroni] listening on :3001
space.update
unable to execute update for space bhag1audapqckgarf7r0: pq: value too long for type character varying(20)
goroutine 11 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc0001ac140, 0x0, 0xba8664, 0xc, 0xd18380, 0xc0002dac40)
        src/github.com/documize/community/edition/logging/logger.go:56 +0x168
github.com/documize/community/domain/space.(*Handler).Update(0xc0001826f0, 0x7fd3d40b8820, 0xc000578010, 0xc000483500)
        src/github.com/documize/community/domain/space/endpoint.go:526 +0x9e1
github.com/documize/community/domain/space.(*Handler).Update-fm(0x7fd3d40b8820, 0xc000578010, 0xc000483500)
        src/github.com/documize/community/server/routing/routes.go:145 +0x48
net/http.HandlerFunc.ServeHTTP(0xc000182ba0, 0x7fd3d40b8820, 0xc000578010, 0xc000483500)
        /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000422150, 0x7fd3d40b8820, 0xc000578010, 0xc000483500)
        src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fd3d40b8820, 0xc000578010, 0xc000483300, 0xc0002da900)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc00040a540, 0x7fd3d40b8820, 0xc000578010, 0xc000483300, 0xc0002da900)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xd19040, 0xc00040a540, 0xc00040a5e0, 0x7fd3d40b8820, 0xc000578010, 0xc000483300)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP-fm(0x7fd3d40b8820, 0xc000578010, 0xc000483300)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc000182690, 0x7fd3d40b8820, 0xc000578010, 0xc000483200, 0xc0004cfc60)
        src/github.com/documize/community/server/middleware.go:228 +0x2d0
github.com/documize/community/server.(*middleware).Authorize-fm(0x7fd3d40b8820, 0xc000578010, 0xc000483200, 0xc0004cfc60)
        src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0001836b0, 0x7fd3d40b8820, 0xc000578010, 0xc000483200, 0xc0004cfc60)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xd19040, 0xc0001836b0, 0xc00040a5c0, 0x7fd3d40b8820, 0xc000578010, 0xc000483200)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc00024b0e0, 0x7fd3d40b8820, 0xc000578008, 0xc000483200)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xee
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003e40e0, 0x7fd3d40b8820, 0xc000578008, 0xc000483200)
        src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fd3d40b8820, 0xc000578008, 0xc00056fc00, 0xc0004cfc20)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc00043cc80, 0x7fd3d40b8820, 0xc000578008, 0xc00056fc00, 0xc0004cfc20)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xd19040, 0xc00043cc80, 0xc00043cce0, 0x7fd3d40b8820, 0xc000578008, 0xc00056fc00)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/vendor/github.com/codegangsta/negr
```

**Comment by sauls8t** [comment]
Go to Postgres and increase the ```dmz_space.c_icon``` column size to 50.

We will update schemas for next point release.

cc @HarveyKandola
