### ISSUE TITLE
unable to fetch request / new install on ubuntu

### ISSUE THREAD

**Issue by vessenes** [documize/community#260]
Hi,

I'm testing the community-linux-amd64 binary with postgres on ubuntu 18.04. Here's how I start the server:

```bash
$ ~/bin/./documize-community-linux-amd64 -port=5001 -db="host=localhost port=5432 dbname=documize user=postgres password=mypass sslmode=disable" -dbtype postgresql
please set DOCUMIZESALT or use -salt with this value: Rcfcfbi9d8eb9fb23
Database: checking state
Database: provider name PostgreSQL
Database: provider version 110002
Database: current version number is 5
Database: loaded 5 SQL scripts for provider PostgreSQL
Database: 0 scripts to process
Extensions: registered 13 section types
Product: Community Edition version 2.4.1 (build 190426114302)
Web Server: starting up
Web Server: binding non-SSL server on 5001
[negroni] listening on :5001
```

When I load the page, I see no HTML, and get the following error message:

```
meta
sql: no rows in result set
goroutine 14 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc00001e640, 0xc0001c6700, 0xc92211, 0x4, 0xe74640, 0xc000064260)
        src/github.com/documize/community/edition/logging/logger.go:56 +0x128
github.com/documize/community/domain/organization.Store.GetOrganizationByDomain(0xc0000dab40, 0x0, 0x0, 0xc0006203c0, 0x3, 0x1a55ac0, 0x0, 0x0, 0xc0005f0d90, 0x4c9f81, ...)
        src/github.com/documize/community/domain/organization/store.go:94 +0x457
github.com/documize/community/domain/meta.(*Handler).Meta(0xc00017e2a0, 0x7f642c113028, 0xc00017c060, 0xc000189000)
        src/github.com/documize/community/domain/meta/endpoint.go:47 +0xd1
net/http.HandlerFunc.ServeHTTP(0xc0003d6700, 0x7f642c113028, 0xc00017c060, 0xc000189000)
        /usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000132310, 0x7f642c113028, 0xc00017c060, 0xc000189000)
        src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f642c113028, 0xc00017c060, 0xc000188e00, 0xc0004204a0)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0005ba0c0, 0x7f642c113028, 0xc00017c060, 0xc000188e00, 0xc0004204a0)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe75740, 0xc0005ba0c0, 0xc0005ba120, 0x7f642c113028, 0xc00017c060, 0xc000188e00)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/server.(*middleware).cors(0xc0003d6600, 0x7f642c113028, 0xc00017c060, 0xc000188e00, 0xc000420480)
        src/github.com/documize/community/server/middleware.go:55 +0x442
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0003d6fc0, 0x7f642c113028, 0xc00017c060, 0xc000188e00, 0xc000420480)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe75740, 0xc0003d6fc0, 0xc0005ba100, 0x7f642c113028, 0xc00017c060, 0xc000188e00)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc000166780, 0x7f642c113028, 0xc00017c058, 0xc000188e00)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xec
github.com/documize/community/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0x7f642c113028, 0xc00017c058, 0xc000188e00)
        src/github.com/documize/community/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc000420460, 0x7f642c113028, 0xc00017c058, 0xc000188e00)
        /usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000132070, 0x7f642c113028, 0xc00017c058, 0xc000188e00)
        src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f642c113028, 0xc00017c058, 0xc000188c00, 0xc000420440)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc00000db60, 0x7f642c113028, 0xc00017c058, 0xc000188c00, 0xc000420440)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xe75740, 0xc00000db60, 0xc00000dbc0, 0x7f642c113028, 0xc00017c058, 0xc000188c00)
        src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
g
unable to fetch request meta for 192
```

Ideas?

**Comment by HarveyKandola** [comment]
Sure, two things:

1. Use config file for passing in params to the binary including SALT value. See this:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/VzSL8cVZ4QAB2B4Y/configuration-options

2. Try to change from using the IP address in your web browser to localhost or host name.

**Comment by vessenes** [comment]
So, what appear to be some bugs:

```bash
~/lib/documize$ ~/bin/documize-community-linux-amd64 ./myconfig.conf

In order to run /home/peter/bin/documize-community-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of /home/peter/bin/documize-community-linux-amd64:
  -cert string
        the cert.pem file used for https
  -db string
        'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
        specify the database provider: mysql|percona|mariadb|postgresql|sqlserver
  -forcesslport string
        redirect given http port number to TLS
  -key string
        the key.pem file used for https
  -location string
        reserved
  -offline string
        set to '1' for OFFLINE mode
  -port string
        http/https port number
  -salt string
        the salt string used to encode JWT tokens, if not set a random value will be generated
```

From this I take away that the binary won't look at the pathname of the config file it's given, that seems like a legit bug?

I then moved the config file to ~/bin:

```bash
~/bin$ ls -l
total 46264
[snip]
-rwxrwxr-x 1 peter peter 29097759 Apr 26 04:46 documize-community-linux-amd64
-rw-rw-r-- 1 peter peter      461 May  1 10:46 documize.conf

~/bin$ ./documize-community-linux-amd64

In order to run ./documize-community-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-community-linux-amd64:
  -cert string
        the cert.pem file used for https
  -db string
        'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
        specify the database provider: mysql|percona|mariadb|postgresql|sqlserver
  -forcesslport string
        redirect given http port number to TLS
  -key string
        the key.pem file used for https
  -location string
        reserved
  -offline string
        set to '1' for OFFLINE mode
  -port string
        http/https port number
  -salt string
        the salt string used to encode JWT tokens, if not set a random value will be generated
```

```
~/bin$ ./documize-community-linux-amd64 documize.conf

In order to run ./documize-community-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-community-linux-amd64:
  -cert string
        the cert.pem file used for https
  -db string
        'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
        specify the database provider: mysql|percona|mariadb|postgresql|sqlserver
  -forcesslport string
        redirect given http port number to TLS
  -key string
        the key.pem file used for https
  -location string
        reserved
  -offline string
        set to '1' for OFFLINE mode
  -port string
        http/https port number
  -salt string
        the salt string used to encode JWT tokens, if not set a random value will be generated
```

For test, I'd like to be able to hit up the server without giving it a DNS record; is that really a requirement that I can't use a 192.x IP address?

**Comment by vessenes** [comment]
FWIW, the enterprise binary does load documize.conf properly. But it has the same error and callstack as community edition on the actual request.

**Comment by vessenes** [comment]
Further update, binding to an IP address and loading changes nothing, only the last line:

```unable to fetch request meta for documize```

**Comment by HarveyKandola** [comment]
Thanks for all the info -- looking into this now...

**Comment by HarveyKandola** [comment]
can you email your conf file to supportATdocumizeDOTcom ?

**Comment by vessenes** [comment]
```yaml
# This configuration file is in TOML format.
#
# Installation guide: https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide

[http]
port = 5001
#forcesslport = 5002
#cert = "selfcert/cert.pem"
#key = "selfcert/key.pem"

[database]
type = "postgresql"
connection = "host=localhost port=5432 dbname=documize user=postgres password=mypass sslmode=disable"
salt = "tsu3Acndky8cdTNx3"

[install]
location = "selfhost"
```

**Comment by HarveyKandola** [comment]
Did you try to place the config file in the same directory as the executable?

```
./documize-enterprise-darwin-amd64 config-postgresql.conf
```

**Comment by vessenes** [comment]
Yes. You can see this in the logs from four days ago; I included the output of `ls`

**Comment by HarveyKandola** [comment]
Thanks for confirming.

If you get in touch with supportATdocumizeDOTcom and someone will get in touch with you.

**Comment by akrabat** [comment]
I'm seeing the same problem:

```
$ ls
documize-community-linux-amd64  documize.conf

$ ./documize-community-linux-amd64 documize.conf

In order to run ./documize-community-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-community-linux-amd64:
  -cert string
    	the cert.pem file used for https
  -db string
    	'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
    	specify the database provider: mysql|percona|mariadb|postgresql|sqlserver
  -forcesslport string
    	redirect given http port number to TLS
  -key string
    	the key.pem file used for https
  -location string
    	reserved
  -offline string
    	set to '1' for OFFLINE mode
  -port string
    	http/https port number
  -salt string
    	the salt string used to encode JWT tokens, if not set a random value will be generated
```

Looks like you can no longer use a config file.

**Comment by mcmatts** [comment]
@akrabat what OS flavor you running?

**Comment by akrabat** [comment]
> @akrabat what OS flavor you running?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by mcmatts** [comment]
@akrabat is Documize binary placed somewhere on your PATH like /usr/local?

**Comment by akrabat** [comment]
@mcmatts No. It's just in a directory with the config file.

**Comment by mcmatts** [comment]
@akrabat thanks

run this in the directory:

```
ls -ls
```

**Comment by mcmatts** [comment]
@akrabat 

if you are using documize.conf as the filename then omit it from the program arguments.

**Comment by akrabat** [comment]
@mcmatts 

```
$ ls -l
total 28420
-rwxrwxr-x 1 rob users 29097759 Apr 26 12:46 documize-community-linux-amd64
-rw-rw-r-- 1 rob users      463 May 10 15:55 documize.conf
```

Also, leaving out the configuration file filename also doesn't work:

```
$ ./documize-community-linux-amd64

In order to run ./documize-community-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-community-linux-amd64:
  -cert string
    	the cert.pem file used for https
  -db string
    	'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
    	specify the database provider: mysql|percona|mariadb|postgresql|sqlserver
  -forcesslport string
    	redirect given http port number to TLS
  -key string
    	the key.pem file used for https
  -location string
    	reserved
  -offline string
    	set to '1' for OFFLINE mode
  -port string
    	http/https port number
  -salt string
    	the salt string used to encode JWT tokens, if not set a random value will be generated
```

**Comment by mcmatts** [comment]
@akrabat @vessenes 

So the issue was the GitHub release did not have v2.4.2 -- that is why the config option did not load.

I just pushed out v2.4.2 release so try that with your config files.

**Comment by akrabat** [comment]
> @akrabat @vessenes
> 
> So the issue was the GitHub release did not have v2.4.2 -- that is why the config option did not load.
> 
> I just pushed out v2.4.2 release so try that with your config files.

That worked! I'm now on version `Community Edition version 2.4.2 (build 190429132654)` and the config file is successfully loading.

Thanks @mcmatts  :)

**Comment by michailw** [comment]
Hello,
I have similar issue. Blank page, Documize doesn't work at all.
Here is what happens on server side:

```
Configuration source: config.conf
Database: checking state
Database: provider name MySQL
Database: provider version 10.4.6-MariaDB-1:10.4.6+maria~xenial
Database: current version number is 31
Database: loaded 32 SQL scripts for provider MySQL
Database: 0 scripts to process
Extensions: registered 13 section types
Product: Community Edition version 3.3.2 (build 191014171946)
Web Server: starting up
Web Server: binding non-SSL server on 5001
[negroni] listening on :5001
unable to fetch request meta for 127
```

My config file:
```
[http]
port = 5001

[database]
type = "mariadb"
connection = "user:password@tcp(localhost:3306)/documize?allowNativePasswords=true"
salt = "mySalt"

[install]
location = "selfhost"
```

On browser side, there is a request to /api/public/meta endpoint, which returns 404.

The error I think I face with is `unable to fetch request meta for 127`.

When I run clean installation of Documize, using same binary (I mean clean DB) it works fine. I need to run on the old one, as there is much content inside already. Can you help me fixing it?

**Comment by sauls8t** [comment]
What is in this SQL table field?

```dmz_org.c_domain```

What happens if you use http://localhost?
