### ISSUE TITLE
JIRA Cloud integration issue

### ISSUE THREAD

**Issue by dpolistbpc** [documize/community#308]
I'm using Documize Community Edition v3.1.2 (build 190805134803).

I have configured JIRA Cloud integration using my user name (email address) and an API Key I've created specifically for Documize.

When trying to add a new JIRA section, the UI shows "Jira connector not authenticated" and I see getting the following error log entries at the server side:

```
Cannot get authenticated Jira user: Specified user does not exist or you do not have required permissions: Request failed. Please analyze the request body for more details. Status code: 404
0|documize-community-linux-amd64  | unable to authenticate with Jira
0|documize-community-linux-amd64  | Specified user does not exist or you do not have required permissions: Request failed. Please analyze the request body for more details. Status code: 404
0|documize-community-linux-amd64  | goroutine 8380 [running]:
0|documize-community-linux-amd64  | github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc00009c690, 0x0, 0xcc9991, 0x20, 0xea2100, 0xc000ac2d80)
0|documize-community-linux-amd64  |     src/github.com/documize/community/edition/logging/logger.go:56 +0x128
0|documize-community-linux-amd64  | github.com/documize/community/domain/section/jira.(*Provider).Render(0xc000368af0, 0xc0016f8b60, 0xcab810, 0x2, 0x0, 0x0, 0xc000e33b01, 0xc0016f8b60)
0|documize-community-linux-amd64  |     src/github.com/documize/community/domain/section/jira/jira.go:69 +0x186
0|documize-community-linux-amd64  | github.com/documize/community/domain/section/provider.Render(0xc000dc7bb8, 0x4, 0xc0016f8b60, 0xcab810, 0x2, 0x0, 0x0, 0x15, 0x1, 0xc00009ee20)
0|documize-community-linux-amd64  |     src/github.com/documize/community/domain/section/provider/provider.go:122 +0xb8
0|documize-community-linux-amd64  | github.com/documize/community/domain/page.(*Handler).Add(0xc00039c220, 0x7f7ed0366860, 0xc00000f3a0, 0xc000cef200)
0|documize-community-linux-amd64  |     src/github.com/documize/community/domain/page/endpoint.go:150 +0x854
0|documize-community-linux-amd64  | net/http.HandlerFunc.ServeHTTP(0xc000369000, 0x7f7ed0366860, 0xc00000f3a0, 0xc000cef200)
0|documize-community-linux-amd64  |     /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003d2cb0, 0x7f7ed0366860, 0xc00000f3a0, 0xc000cef200)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f7ed0366860, 0xc00000f3a0, 0xc000cef000, 0xc000571380)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0005585c0, 0x7f7ed0366860, 0xc00000f3a0, 0xc000cef000, 0xc000571380)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xea2e40, 0xc0005585c0, 0xc000558620, 0x7f7ed0366860, 0xc00000f3a0, 0xc000cef000)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
0|documize-community-linux-amd64  | github.com/documize/community/server.(*middleware).Authorize(0xc000368d30, 0x7f7ed0366860, 0xc00000f3a0, 0xc000ceef00, 0xc000570ea0)
0|documize-community-linux-amd64  |     src/github.com/documize/community/server/middleware.go:228 +0x268
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc000369c80, 0x7f7ed0366860, 0xc00000f3a0, 0xc000ceef00, 0xc000570ea0)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xea2e40, 0xc000369c80, 0xc000558600, 0x7f7ed0366860, 0xc00000f3a0, 0xc000ceef00)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc000549bf0, 0x7f7ed0366860, 0xc00000f398, 0xc000ceef00)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xec
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0x7f7ed0366860, 0xc00000f398, 0xc000ceef00)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x10d
0|documize-community-linux-amd64  | net/http.HandlerFunc.ServeHTTP(0xc000570e80, 0x7f7ed0366860, 0xc00000f398, 0xc000ceef00)
0|documize-community-linux-amd64  |     /usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00016ba40, 0x7f7ed0366860, 0xc00000f398, 0xc000ceef00)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f7ed0366860, 0xc00000f398, 0xc000ceed00, 0xc000570e60)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc000570aa0, 0x7f7ed0366860, 0xc00000f398, 0xc000ceed00, 0xc000570e60)
0|documize-community-linux-amd64  |     src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
0|documize-community-linux-amd64  | github.com/documize/community/vendor/github.com/codegangsta/neg

```

**Comment by HarveyKandola** [comment]
```Specified user does not exist or you do not have required permissions:```

Double check that the Jira user being used is an administrator?

**Comment by HarveyKandola** [comment]
Thought as much!

To be clear: Provide API Token if using Atlassian Cloud or Password when self-hosting Jira.

We  have just upgraded the Jira library dependency in a bid to ensure we have all latest fixes. Long shot, but hey...

New release v3.2.0 drops this coming weekend.

**Comment by kaissi** [comment]
I'm getting this exact issue when trying to add a new JIRA section. It shows "Jira connector not authenticated".

I'm using the online version of Documize Enterprise Edition and JIRA Cloud.

I created an API Token in JIRA Cloud and tested with curl. Works perfectly, but doesn't work in Documize. When I create a new JIRA section, the field "Last accessed" in JIRA is refreshed to "few seconds ago", but it keeps showing in Documize "Jira connector not authenticated".
